### PR TITLE
implement CREATE_NEW_ASSET_IF_MISSING for asset status module

### PR DESCRIPTION
**Pull request by clarkbynum**

### CODE REVIEW

**Comment by sh3nan1gans** [comment]
@savfaire @yashjain28 is it possible that the status SS and the location SS have a race condition where if the flag is turned on for both, both could create the same asset?

**Comment by yashjain28** [comment]
yes, it is possible that's why I didn't have it turned on for both of them.

**Comment by sh3nan1gans** [comment]
Ok, I remember having that discussion a few months ago. We should consider combining asset status and asset location somehow

**Comment by sh3nan1gans** [comment]
We could either combine asset status and asset location or push this logic into the normalizer

**Comment by yashjain28** [comment]
I am for combining asset status and location, it'll also reduce the collection updates by 1 for every message. @sh3nan1gans

**Pull request merged**
